---
- name: Setup Demo Pi
  hosts: demopi
  become: yes

  handlers:
    - name: reboot
      reboot:

  tasks:
    - name: Change the password hashing algorithm
      lineinfile:
        path: /etc/login.defs
        regex: '^ENCRYPT_METHOD\s[A-Z,0-9]*'
        firstmatch: yes
        line: 'ENCRYPT_METHOD YESCRYPT'

    - name: Configure the hostname
      block:
        - name: Set the hostname
          hostname:
            name: demopi

        - name: Set the hostname local route in /etc/hosts
          lineinfile:
            path: /etc/hosts
            insertafter: '^127\.0\.0\.1\slocalhost'
            firstmatch: yes
            regex: '^127\.0\.1\.1\s[a-z]*'
            line: '127.0.1.1	demopi'
      notify: reboot

    - name: Add an unprivileged user
      user:
        name: demo
        comment: 'Automotive Cyberphysical and Embedded Security (ACES)'
        create_home: yes
        state: present

    # Follows the `do_boot_behaviour()` function from `raspi-config`
    # (see https://github.com/RPi-Distro/raspi-config/blob/bookworm/raspi-config)
    - name: Configure the desktop environment for unprivileged autologin
      block:
        - name: Ensure the display manager is installed
          package:
            name: lightdm
            state: latest

        # Systemd targets are not supported, manipulate symlinks directly
        # (see https://stackoverflow.com/questions/64701241/how-do-i-write-ansible-task-for-systemctl-set-default-graphical-target-without/64701430#64701430)
        - name: Enable the graphical environment
          file:
            src: /lib/systemd/system/graphical.target
            dest: /etc/systemd/system/default.target
            state: link

        - name: Set the autologin user
          lineinfile:
            path: /etc/lightdm/lightdm.conf
            regex: '^#?autologin-user='
            line: 'autologin-user=demo'

        - name: Configure the autologin service
          copy:
            src: files/raspios/etc/systemd/system/getty@tty1.service.d/autologin.conf
            dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
      notify: reboot
