---
- name: Setup the GPS Spoofing demo
  hosts: demopi
  become: yes

  handlers:
    # Remove the executable, so it gets rebuilt
    - name: rebuild
      file:
        path: /opt/demo/gps-spoof/gps-sdr-sim/gps-sdr-sim
        state: absent

  tasks:
    - name: Have the build tools at hand
      package:
        name:
          - build-essential
          - git
        state: latest

    - name: Create the install directory
      file:
        path: /opt/demo/gps-spoof
        owner: root
        group: demo
        mode: 0755
        state: directory

    - name: Fetch the GPS simulation software
      git:
        repo: https://github.com/osqzss/gps-sdr-sim.git
        dest: /opt/demo/gps-spoof/gps-sdr-sim
        depth: 1
        force: yes
      notify: rebuild

    - name: Run the rebuild handler, if necessary
      meta: flush_handlers

    - name: Build the GPS simulation software
      command:
        chdir: /opt/demo/gps-spoof/gps-sdr-sim
        cmd: gcc gpssim.c -lm -O3 -o gps-sdr-sim
        creates: gps-sdr-sim
